on:
  workflow_run:
    workflows: ["Lint"]
    branches: [main]
    types:
      - completed

name: Docker build and push
jobs:
  build:
    name: Docker build and push
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        # Currently ghcr.io only supports a personal access token, so
        # this is one from reload-deploy.
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push Docker images
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        tags: |
          ghcr.io/reload/${{ github.repository}}:latest
        push: true
