on:
  workflow_run:
    workflows: ["Lint"]
    branches: [v2]
    types:
      - completed

name: Docker build and push
jobs:
  build:
    name: Docker build and push
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      id: version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/v2'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        # Currently ghcr.io only supports a personal access token, so
        # this is one from reload-deploy.
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push Docker images
      if: github.ref == 'refs/heads/v2'
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ steps.version.outputs.tag }}
          org.opencontainers.image.revision=${{ github.sha }}
        tags: |
          ghcr.io/${{ github.repository }}:v2
          ghcr.io/${{ github.repository }}:${{ steps.version.outputs.tag }}
