on: push
name: Lint

jobs:
  dockerfile-lint:
    name: dockerfile
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Run hadolint
       uses: brpaz/hadolint-action@v1.5.0

  test:
    name: Build image and test basic functionality
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    needs: dockerfile-lint
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Test building image
      run: |
        docker build -t testimage .
